{% set name = "pyinstaller-hooks-contrib" %}
{% set version = "2024.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyinstaller/pyinstaller-hooks-contrib/archive/v{{ version }}.tar.gz
  sha256: 236d72ac61ed0d81ea2f6836c5f34607e51bfdf8e0f642ed4eb66373959b5996

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - setuptools >=42.0.0
    - importlib_metadata >=4.6
    - packaging >=22.0

test:
  imports:
    - _pyinstaller_hooks_contrib
    - _pyinstaller_hooks_contrib.hooks

about:
  home: https://github.com/pyinstaller/pyinstaller-hooks-contrib
  summary: Community maintained hooks for PyInstaller
  license: Apache-2.0 OR GPL-2.0-or-later
  license_file:
    - LICENSE.GPL.txt
    - LICENSE.APL.txt
  description: |
    A "hook" file extends PyInstaller to adapt it to the special needs and
    methods used by a Python package. The word "hook" is used for two kinds of
    files. A runtime hook helps the bootloader to launch an app, setting up the
    environment. A package hook (there are several types of those) tells
    PyInstaller what to include in the final app - such as the data files and
    (hidden) imports mentioned above.
  doc_url: https://github.com/pyinstaller/pyinstaller-hooks-contrib/wiki
  dev_url: https://github.com/pyinstaller/pyinstaller-hooks-contrib

extra:
  recipe-maintainers:
    - nehaljwani
